#!/bin/sh /etc/rc.common

START=90
STOP=10

USE_PROCD=1

error() {
    echo "${initscript}:" "$@" 1>&2
}

start_service() {
    config_load 'audio-streamer'

    local enabled
    config_get_bool enabled 'settings' 'enabled' 0
    [ "$enabled" -gt 0 ] || return

    local port device channels rate format
    config_get port 'settings' 'port'
    config_get device 'settings' 'device' 'default'
    config_get channels 'settings' 'channels' '1'
    config_get rate 'settings' 'rate' '16000'
    config_get format 'settings' 'format' 'S16_LE'

    if [ -z "$port" ]; then
        error "Missing port in config"
        return 1
    fi

    procd_open_instance "audio-streamer"
    procd_set_param command /bin/sh -c "arecord -D $device -f $format -c $channels -r $rate -t raw | netcat -l -p $port"
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-0}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger 'audio-streamer'
}
